FROM debian:bookworm-slim

ENV ALLSHARE_PATH=/allshare

# Create a non-root user
RUN groupadd -r allshare && useradd -r -g allshare -d ${ALLSHARE_PATH} -s /sbin/nologin allshare

# Create / Go to app directory
WORKDIR ${ALLSHARE_PATH}

# Copy prebuilt artifacts
COPY allshare/ ${ALLSHARE_PATH}/

# Mark executables as executable, create server directory, and change ownership
RUN chmod +x ${ALLSHARE_PATH}/allshare && \
    mkdir -p ${ALLSHARE_PATH}/server && \
    chown -R allshare:allshare ${ALLSHARE_PATH}

# Create a volume with the config.json and data.json
VOLUME ${ALLSHARE_PATH}/server

# Expose the port (adjust if you changed it)
ENV WEBRTC_PORT_RANGE=40000:40100
EXPOSE 8080 40000-40100/udp

# Create an entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Switch to the non-root user
USER allshare

# Run the binary
ENTRYPOINT ["/entrypoint.sh"]
